---
title: "Simulating bayesian hybrid flies"
author: "Allen and Andrew"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

## studying the gamma distribution

```{r}
gamma_var <- rgamma(n = 570, shape = 6, scale = 1.5)

gamma_var |> mean()
gamma_var |> sd()

# theoretical average
6*1.5

# theory sd
sqrt(6*1.5^2)

```


browseVignettes()

see the [brms vignettes](https://cran.r-project.org/web/packages/brms/vignettes/brms_families.html)


brms uses mean $\mu$ rate = $\alpha/\mu$

```{r}

a <- 3
m <- 16
xx <- rgamma(571, shape = m^2/a^2, rate = m/a^2)
hist(xx)
mean(xx)
sd(xx)

```


```{r}
library(brms)

gamma_form <- bf(xx ~ 1,
                 family = brmsfamily("Gamma",
                                     link = "log",
                                     link_shape = "log")) + 
  lf(shape ~ 1)

simple_gamma <- brm(gamma_form, 
                    data = data.frame(xx), 
                    backend = "cmdstanr", cores = 4)

summary(simple_gamma)
# intercept = 2.19, shape = 87.27
```


ANdrew is going to ask in the Stan forum WTF is happening when you use the gamma family -- why does LF behave differently thank the alternative

```{r}
library(tidybayes)

simple_gamma |> get_variables()

# gather_draws(simple_gamma, b_Intercept, b_shape_Intercept)

gather_rvars(simple_gamma, b_Intercept, b_shape_Intercept) |> 
  mutate(.value = exp(.value),
         true_vals =  c(m, m^2/a^2)) |> 
  ggplot(aes(y = .variable, dist = .value))  + 
  stat_dist_dots() + 
  facet_wrap(~.variable, scales = "free") + 
  geom_vline(aes(xintercept = true_vals))

```

```{r}
# stancode(simple_gamma)
```

## prior simulations

```{r}
get_prior(gamma_form, data = data.frame(xx))

andrew_prior <- c(prior(normal(2, .3), class = "Intercept"),
                  prior(normal(2, .4), class = "Intercept", dpar = "shape"))
```

```{r}
# visualizing in base R 

rnorm(4000, mean = 2, sd = .2) |> exp() |> hist()
```


```{r}

gamma_form <- bf(xx ~ 1,
                 family = brmsfamily("Gamma",
                                     link = "log",
                                     link_shape = "log")) + 
  lf(shape ~ 1)

gamma_prior_predict <- brm(gamma_form, data = data.frame(xx), 
    prior = andrew_prior,
    backend = "cmdstanr", cores = 4, sample_prior = "only")

# visualize
gamma_prior_predict |> 
  gather_draws( b_Intercept, b_shape_Intercept, ndraws = 6)

data.frame(nn = 1:450) |> 
  add_predicted_draws(gamma_prior_predict, ndraws = 12) |> 
  ggplot(aes(x = .prediction)) + 
  geom_histogram() + 
  facet_wrap(~.draw, ncol = 4)

```



